### ISSUE TITLE
Broken Reference - Most popular BugSnag event is this module itself

### ISSUE THREAD

**Issue by InternetMedicineMan** [interjar/bugsnag-magento2#12]
I get this error constantly. Like more than 116,000 times a month.

Broken reference: No element found with ID 'customer'. /chroot/home/wonderci/retailer.wondercide.com/html/vendor/interjar/bugsnag/Bugsnag/Handler.php:88 Interjar\BugSnag\Bugsnag\Handler::write

Does this module just not work properly?

**Comment by josh-carter** [comment]
@InternetMedicineMan The error you're seeing is nothing to do with the extension I'm afraid.

Thats a pretty common Magento 2 error coming from your theme. My guess is somewhere in your theme there is some layout XML referencing a Block or a Container with the name `customer`. This Block/Container mustn't exist on the page and is therefore throwing an error every time a page is hit.

The reason you see the path to the Bugsnag Handler is because that's where the error is caught and reported.

**Comment by InternetMedicineMan** [comment]
Oh okay, So the module isn't broken, it just isn't smart enough to give real information. That's kind of worse than broken, kind of makes it pointless.

**Comment by josh-carter** [comment]
@InternetMedicineMan Have you taken a look in your Bugsnag dashboard by any chance? You'll see the full trace to follow so that you can debug, further than you could if you didn't have the module installed.

I'm not asking you to use the extension, I'm simply providing a solution for you to use rather than you having to write one yourself. If you feel like its pointless don't use it, but in my opinion its far from pointless.

**Comment by InternetMedicineMan** [comment]
Yeah I have looked at it. It doesn't trace back to any XML file, or any theme files for that matter, and I'm just using the Luma theme, I have a few overrides in place but nothing that references an id called customer. I don't understand how an error can get caught by something completely unrelated and not even exist in the full trace, but it's out there somewhere else. 

Doesn't appear to be of much value, but maybe it is to a more seasoned dev.

**Comment by josh-carter** [comment]
If you're using XDebug then hit the site with a few breakpointa inside `Magento\Framework\View\Layout\GeneratorPool::moveElementInStructure(...){...}` - If not, go to `Magento\Framework\View\Layout\GeneratorPool::moveElementInStructure(...){...}` where its catching the exception and logging the error, dump what the elements are etc. and it should point you to where your broken XML is. 

Magento does have a couple of these Broken Reference errors throughout the Luma theme as far as im aware. But its not really anything to worry about, the XML will just be skipped out from the generated XML.

Based off the Stack Trace it gives you it shouldn't be too difficult to debug. The extension definitely isn't pointless if you're using Bugsnag to its capabilities, if not for anything else - especially for instances like this where, without it, Magento would log a one line 'Broken Reference' error, no Stack trace or anything. From the trace it provides you can get a good enough idea of whats gone wrong.

It should even give you the controller action which initialised the layout, if the error isn't happening on every page that'll almost point you to the file in which its occurring. 

As i said, Im not making you use the extension, or even telling you to use it. The module is just here if you need to hook M2 to Bugsnag and don't have any other solution.
